### ISSUE TITLE
Add a blog functionnality

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/website#5]
# Context

To write technical articles

# Todo
- [x] install symfony
- [ ] install easyadmin
- [ ] add blog theme
- [ ] index blog post
- [ ] show blog post
